/*
@TargetNode='localhost'
@GeneratedBy=eric.anllo-muniz
@GenerationDate=09/18/2025 15:36:05
@GenerationHost=C11-LFXFXPNOPXA
*/

instance of MSFT_ScriptResource as $MSFT_ScriptResource1ref
{
SetScript = "return $true";
 ResourceID = "[Script]CheckSBL";
 SourceInfo = "C:\\Users\\eric.anllo-muniz\\OneDrive - Accenture\\Desktop\\DIGIT\\AzureLandingZone\\Definitions\\policyDefinitions\\SLZ\\Guest-Configuration\\ID741\\Audit.ps1::6::5::Script";
 GetScript = "$path = \"HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging\"\n$val  = (Get-ItemProperty -Path $path -Name EnableScriptBlockLogging -ErrorAction SilentlyContinue).EnableScriptBlockLogging\n@{ Result = $(if($null -eq $val) { \"NotConfigured\" } else { \"EnableScriptBlockLogging=$val\" }) }";
 ModuleName = "PSDscResources";
 ModuleVersion = "2.12.0.0";
 TestScript = "$path = \"HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging\"\n$val  = (Get-ItemProperty -Path $path -Name EnableScriptBlockLogging -ErrorAction SilentlyContinue).EnableScriptBlockLogging\nreturn ([int]$val -eq 1)";
 ConfigurationName = "Audit_ScriptBlockLogging_Enabled";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="eric.anllo-muniz";

                        GenerationDate="09/18/2025 15:36:05";

                        GenerationHost="C11-LFXFXPNOPXA";

                        Name="Audit_ScriptBlockLogging_Enabled";

                    };
